version: '3.3'

services:
    mailcatcher:
        image: docker.io/schickling/mailcatcher
        ports:
            - 1080:1080
            - 1025:1025

    db:
        image: mariadb:10.5.8
        restart: always
        environment:
            MYSQL_DATABASE: 'test_festival'
            MYSQL_USER: 'festival'
            MYSQL_PASSWORD: '1rDS3yHAdVaMX5Ey'
            MYSQL_ROOT_PASSWORD: 'puAx0aWi8E6CTw3V'
        ports:
            - '3306:3306'
        expose:
            - '3306'
        volumes:
            - db_test_festival:/var/lib/mysql

    adminpanel:
        depends_on:
            - 'admindb'
        image: 'motoradmin/motoradmin:latest'
        ports:
            - '3001:3000'
        volumes:
            - '.:/app'
        env_file:
            - .env
        environment:
            DATABASE_URL: postgresql://postgres:postgres@admindb:5432/motoradmin

    admindb:
        image: 'postgres:13.4'
        volumes:
            - 'postgres:/var/lib/postgresql/data'
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: motoradmin

volumes:
    db_test_festival:
    postgres:
